# -*- coding: utf-8 -*-
"""
Created on Tue Aug 18 14:21:41 2020
@author: Yuri
Do not edit this file =)

HAVE FUN KNOWING YOURSELF!!! :)
CLICK THE PLAY BUTTON
"""
from script import self_ref
